<?php

namespace common\models;


use common\classes\Debug;
use Yii;

/**
 * This is the model class for table "logo".
 *
 * @property int $id
 * @property int $company_id
 * @property string $image
 * @property int $active_until
 *
 * @property Company $company
 */
class Logo extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'logo';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['company_id'], 'integer'],
            [['active_until'], 'date', 'format' => 'y-m-d'],
            [['image'], 'string', 'max' => 255],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => Company::className(), 'targetAttribute' => ['company_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'company_id' => 'Компания',
            'image' => 'Логотип',
            'active_until' => 'Активен до',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(Company::className(), ['id' => 'company_id']);
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        $this->active_until = strtotime($this->active_until);

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
