<?php
namespace common\models;

use Yii;

/**
 * This is the model class for table "news".
 *
 * @property int $id
 * @property string $title
 * @property string $description
 * @property string $content
 * @property int $status
 * @property int $dt_create
 * @property int $dt_update
 */
class News extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'news';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'content'], 'required'],
            [['title', 'description', 'content'], 'string'],
            [['status', 'dt_create', 'dt_update'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Название',
            'description' => 'Описание',
            'content' => 'Содержание',
            'status' => 'Status',
            'dt_create' => 'Дата создание',
            'dt_update' => 'Дата редактирования',
        ];
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        if($this->dt_create !== null) {
            $this->dt_create = date('d-m-Y', $this->dt_create);
        }

        if($this->dt_update !== null) {
            $this->dt_update = date('d-m-Y', $this->dt_update);
        }
    }
}
